
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /web_start
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./backend/.env.local
    depends_on:
      - redis
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:7-alpine
    expose:
      - 6379
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /celery_start
    image: web
    env_file:
      - ./backend/.env.local
    depends_on:
      - redis
      - db
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /flower_start
    image: web
    env_file:
      - ./backend/.env.local
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /celery_beat_start
    image: web
    env_file:
      - ./backend/.env.local
    depends_on:
      - redis
      - db
  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
      - redis
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: front
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: