# Generated by Django 4.2.13 on 2024-10-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPriceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('card_condition', models.CharField(max_length=10)),
                ('card_language', models.CharField(max_length=20)),
                ('card_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('seller_profile_link', models.CharField(max_length=100)),
                ('seller_country', models.CharField(max_length=50)),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardprinting')),
            ],
        ),
    ]
